const jobTitleMapping = {
    "Adjudicator": "ADMN O 18R",
    "Admin & Asset Administrator": "CLK 12R",
    "Administrative Assistant": "CLK ST 09R",
    "Assistant Supervisor": "CPO-IA 21R",
    "Branch Coordinator": "CLK ST 12R",
    "Business Application Admin": "ADMN O 15R",
    "Business Data Analyst": "FO 18R",
    "Client Service Representative": "CLK 09R",
    "Client Service Worker": "CLK 09R",
    "Community Relations & Stakeholder Analysis": "ADMN O 24R",
    "Communications & Engagement Analyst": "COMM O 18R",
    "Communications Analyst": "COMM O 18R",
    "Community Integration Specialist": "CPO 18R",
    "Contract Analyst": "ADMN O 18R",
    "Data Analyst": "RES O 21R",
    "Director, Partnership, Performance & Practice": "Band 4",
    "Director, Strategic Projects & Technology Integration": "Band 4",
    "Director, Strategic Partnerships & Communications": "Band 4",
    "Director, Communications Engagement & Organizational Health": "Band 3",
    "Director, Knowledge Management": "Band 3",
    "Director, ABI": "Band 4",
    "Director, Criminal Operations": "Band 4",
    "Director, FCR": "Band 4",
    "Director, Operations": "Band 4",
    "Director, Program Integrity & Evaluation": "Band 4",
    "Director, RSFA": "Band 4",
    "Director, Service Delivery": "Band 4",
    "Employment & Assistance Worker": "CPO-EA 15R",
    "Executive Administrative Assistant": "EXEC ADMIN",
    "Facilities & Assets Admin": "CLK 12R",
    "Facilities & Assets Coordinator": "CLK 15R",
    "Financial Analyst": "FO 18R",
    "Full Stack Developer": "ISL 27R",
    "Job Resources Analyst": "ADMN O 18R",
    "Job Resources Lead": "ADMN O 24R",
    "Junior Performance Analyst": "RES O 18R",
    "Junior Program Analyst": "EQU INTERN",
    "Lead Trainer": "ADMN O 21R",
    "Major Case File Specialist": "ADMN O 18R",
    "Manager, Learning & Development": "Band 2",
    "Manager, Strategy Planning & Projects": "Band 2",
    "Manager, Analytics & BI": "Band 3",
    "Manager, Contracts": "Band 3",
    "Manager, Criminal Operations": "Band 3",
    "Manager, Data & Evaluation": "Band 3",
    "Manager, Facilities & Assets": "Band 3",
    "Manager, Financial Services": "Band 3",
    "Manager, Operations": "Band 3",
    "Manager, Policy & Program Implementation": "Band 2",
    "Manager, Program Evaluation": "Band 3",
    "Manager, Program Integrity": "Band 3",
    "Manager, Recruitment": "Band 3",
    "Manager, SD & Program Development": "Band 3",
    "Manager, Senior Project": "Band 2",
    "Manager, Service Delivery": "Band 3",
    "Manager, Staffing": "Band 3",
    "Manager, Strategic Issues": "Band 2",
    "Manager, Trainer Program": "Band 2",
    "Manager, Business Technology Integration": "Band 3",
    "Manager, Program Evaluation & Reportng": "Band 3",
    "Manager, Community Relations & Service Quality": "Band 2",
    "Manager, Organizational Health & Development": "Band 2",
    "Manager, Partnerships & Practice": "Band 3",
    "Marketing Leader": "ADMN O 21R",
    "Ministry Investigator": "ADMN O 21R",
    "Operations Support Clerk": "CLK 09R",
    "Policy & Communications Coordinator": "ADMN O 18R",
    "Policy & Project Analyst": "ADMN O 21R",
    "Policy Interpretation & Coordination Analyst": "ADMN O 18R",
    "Process & Project Analyst": "ADMN O 18R",
    "Program & Policy Analyst": "ADMN O 24R",
    "Program Evaluation Analyst": "ADMN O 24R",
    "Program Evaluation Specialist": "RES O 18R",
    "Program Specialist": "ADMN O 18R",
    "Program Support Clerk": "CLK 09R",
    "Program Support Supervisor": "CLK 15R",
    "Project Analyst": "ADMN O 18R",
    "Project Management & Analysis Support": "WAIP",
    "Project Management Analyst": "ADMN O 21R",
    "Project Support Analyst": "EQU INTERN",
    "Project Support Intern": "IY INTERN",
    "Quality & Compliance Specialist": "AO-IO R18",
    "Records Clerk": "CLK 09R",
    "Records Management Supervisor": "CLK 15R",
    "Recruitment & Staffing Analyst": "FO 18R",
    "Recruitment & Staffing Clerk": "CLK 09R",
    "Recruitment & Staffing Coordinator": "CLK 15R",
    "Recruitment & Staffing Supervisor": "ADMN O 24R",
    "Research Analyst": "RES O 21R",
    "Research & Project Support": "WAIP",
    "Senior Budget Analyst": "FO 24R",
    "Senior Business Analyst": "ADMN O 24R",
    "Senior Data Analyst": "RES O 24R",
    "Senior Data Architect": "ISL 27R",
    "Senior Investigator": "ADMN O 24R",
    "Senior Ministry Investigator": "ADMN O 24R",
    "Senior Policy & Program Specialist": "POL SI 27R",
    "Senior Policy & Project Analyst": "ADMN O 24R",
    "Senior Program Analyst": "ADMN O 24R",
    "Senior Project Management Analyst": "ADMN O 24R",
    "Senior Data Architect & Data Scientist": "ISL 27R",
    "Senior Business Intelligence Analyst": "RES O 24R",
    "Senior Facilities & Asset Coordinator": "ADMN O 18R",
    "Senior Financial Contract Analyst": "ADMN O 24R",
    "Senior Manager, Community Relations & Program Coordination": "Band 3",
    "Senior Manager, Policy Interpretation & Implementation": "Band 3",
    "Senior Policy & Project Analyst": "ADMN O 24R",
    "Senior Policy & Project Specialist": "POL SI 27R",
    "Senior Project Management Advisor": "ADMN O 24R",
    "Senior Records Management Analyst": "ADMN O 21R",
    "Senior Financial Contract Analyst": "ADMN O 24R",
    "Supervisor, Criminal Investigations": "ADMN O 27R",
    "Supervisor, Admin Services": "CLK 15R",
    "Supervisor, Business Insights": "ADMN O 24R",
    "Supervisor, Prevention & Compliance": "ADMN O 24R",
    "Supervisor, Program Support": "CLK 15R",
    "Supervisor, Service Delivery": "CPO-IA 24R",
    "Team Lead, Program Evaluation": "ADMN O 24R",
    "Trainer": "ADMN O 18R",
    "Training Coordinator": "ADMN O 15R",
    "Training Specialist": "ADMN O 21R",
    "Unit Administrator": "CLK 12R",
    "Workplace Health Advisor": "ADMN O 18R",
    "Other": "-"
  };
  
  export default jobTitleMapping;
  