import React from 'react';

const jobTitleOptions = [
    { value: '', label: 'Please Select:' },
    { value: 'Adjudicator', label: 'Adjudicator' },
    { value: 'ADM Service Delivery Division', label: 'ADM Service Delivery Division' },
    { value: 'Admin & Asset Administrator', label: 'Admin & Asset Administrator' },
    { value: 'Administrative Assistant', label: 'Administrative Assistant' },
    { value: 'Assistant Supervisor', label: 'Assistant Supervisor' },
    { value: 'Branch Coordinator', label: 'Branch Coordinator' },
    { value: 'Business Application Admin', label: 'Business Application Admin' },
    { value: 'Business Data Analyst', label: 'Business Data Analyst' },
    { value: 'Client Service Representative', label: 'Client Service Representative' },
    { value: 'Client Service Worker', label: 'Client Service Worker' },
    { value: 'Comm Relat and Stakehol Analys', label: 'Comm Relat and Stakehol Analys' },
    { value: 'Comms & Engagement Analyst', label: 'Comms & Engagement Analyst' },
    { value: 'Communications Analyst', label: 'Communications Analyst' },
    { value: 'Community Integration Special', label: 'Community Integration Special' },
    { value: 'Contract Analyst', label: 'Contract Analyst' },
    { value: 'Data Analyst', label: 'Data Analyst' },
    { value: 'Dir Partnership, Perf & Prac', label: 'Dir Partnership, Perf & Prac' },
    { value: 'Dir, Strat Proj & Tech Integra', label: 'Dir, Strat Proj & Tech Integra' },
    { value: 'Dir, Strategic Partner & Comms', label: 'Dir, Strategic Partner & Comms' },
    { value: 'Dir. Comm Engage & Org Health', label: 'Dir. Comm Engage & Org Health' },
    { value: 'Dir. Knowledge Management', label: 'Dir. Knowledge Management' },
    { value: 'Director, ABI', label: 'Director, ABI' },
    { value: 'Director, Criminal Operations', label: 'Director, Criminal Operations' },
    { value: 'Director, FCRM', label: 'Director, FCRM' },
    { value: 'Director, Operations', label: 'Director, Operations' },
    { value: 'Director, Prg Integrity & Eval', label: 'Director, Prg Integrity & Eval' },
    { value: 'Director, RSFA', label: 'Director, RSFA' },
    { value: 'Director, Service Delivery', label: 'Director, Service Delivery' },
    { value: 'ED, Community Integration Serv', label: 'ED, Community Integration Serv' },
    { value: 'Employment & Assistance Worker', label: 'Employment & Assistance Worker' },
    { value: 'Exec Dir Operations Support', label: 'Exec Dir Operations Support' },
    { value: 'Executive Administrative Asst', label: 'Executive Administrative Asst' },
    { value: 'Executive Director, PLMS', label: 'Executive Director, PLMS' },
    { value: 'Executive Director, SD', label: 'Executive Director, SD' },
    { value: 'Executive Director, SS', label: 'Executive Director, SS' },
    { value: 'Facilities & Asset Admin', label: 'Facilities & Asset Admin' },
    { value: 'Facilities &Assets Coordinator', label: 'Facilities &Assets Coordinator' },
    { value: 'Financial Analyst', label: 'Financial Analyst' },
    { value: 'Full Stack Developer', label: 'Full Stack Developer' },
    { value: 'Job Resources Analyst', label: 'Job Resources Analyst' },
    { value: 'Job Resources Lead', label: 'Job Resources Lead' },
    { value: 'Jr Performance Analyst', label: 'Jr Performance Analyst' },
    { value: 'Junior Program Analyst', label: 'Junior Program Analyst' },
    { value: 'Lead Trainer', label: 'Lead Trainer' },
    { value: 'Major Case File Specialist', label: 'Major Case File Specialist' },
    { value: 'Manager Learning & Development', label: 'Manager Learning & Development' },
    { value: 'Manager Strateg Plan & Project', label: 'Manager Strateg Plan & Project' },
    { value: 'Manager, Analytics and BI', label: 'Manager, Analytics and BI' },
    { value: 'Manager, Contracts', label: 'Manager, Contracts' },
    { value: 'Manager, Criminal Operations', label: 'Manager, Criminal Operations' },
    { value: 'Manager, Data & Evaluation', label: 'Manager, Data & Evaluation' },
    { value: 'Manager, Facilities and Assets', label: 'Manager, Facilities and Assets' },
    { value: 'Manager, Financial Services', label: 'Manager, Financial Services' },
    { value: 'Manager, Operations', label: 'Manager, Operations' },
    { value: 'Manager, Policy & Pgm Impl', label: 'Manager, Policy & Pgm Impl' },
    { value: 'Manager, Program Evaluation', label: 'Manager, Program Evaluation' },
    { value: 'Manager, Program Integrity', label: 'Manager, Program Integrity' },
    { value: 'Manager, Recruitment', label: 'Manager, Recruitment' },
    { value: 'Manager, SD & Program Devel', label: 'Manager, SD & Program Devel' },
    { value: 'Manager, Senior Project', label: 'Manager, Senior Project' },
    { value: 'Manager, Service Delivery', label: 'Manager, Service Delivery' },
    { value: 'Manager, Staffing', label: 'Manager, Staffing' },
    { value: 'Manager, Strategic Issues', label: 'Manager, Strategic Issues' },
    { value: 'Manager, Trainer Program', label: 'Manager, Trainer Program' },
    { value: 'Marketing Leader', label: 'Marketing Leader' },
    { value: 'Mgr Bus Technology Integration', label: 'Mgr Bus Technology Integration' },
    { value: 'Mgr Prgm Evaluation & Reportng', label: 'Mgr Prgm Evaluation & Reportng' },
    { value: 'Mgr, Comm Rel & Service Qual', label: 'Mgr, Comm Rel & Service Qual' },
    { value: 'Mgr, Org Health & Development', label: 'Mgr, Org Health & Development' },
    { value: 'Mgr, Partnerships & Practice', label: 'Mgr, Partnerships & Practice' },
    { value: 'Ministry Investigator', label: 'Ministry Investigator' },
    { value: 'Operations Support Clerk', label: 'Operations Support Clerk' },
    { value: 'Policy & Comms Coordinator', label: 'Policy & Comms Coordinator' },
    { value: 'Policy & Project Analyst', label: 'Policy & Project Analyst' },
    { value: 'Policy Interp & Coord Analyst', label: 'Policy Interp & Coord Analyst' },
    { value: 'Process & Project Analyst', label: 'Process & Project Analyst' },
    { value: 'Prog and Policy Analyst (Dev)', label: 'Prog and Policy Analyst (Dev)' },
    { value: 'Program and Policy Analyst', label: 'Program and Policy Analyst' },
    { value: 'Program Evaluation Analyst', label: 'Program Evaluation Analyst' },
    { value: 'Program Evaluation Specialist', label: 'Program Evaluation Specialist' },
    { value: 'Program Specialist', label: 'Program Specialist' },
    { value: 'Program Support Clerk', label: 'Program Support Clerk' },
    { value: 'Program Support Supervisor', label: 'Program Support Supervisor' },
    { value: 'Proj Mgmt and Analysis Support', label: 'Proj Mgmt and Analysis Support' },
    { value: 'Project Analyst', label: 'Project Analyst' },
    { value: 'Project Management Analyst', label: 'Project Management Analyst' },
    { value: 'Project Support Analyst', label: 'Project Support Analyst' },
    { value: 'Project Support Intern', label: 'Project Support Intern' },
    { value: 'Quality and Compliance Spec', label: 'Quality and Compliance Spec' },
    { value: 'Records Clerk', label: 'Records Clerk' },
    { value: 'Records Management Supervisor', label: 'Records Management Supervisor' },
    { value: 'Recruitment & Staffing Analyst', label: 'Recruitment & Staffing Analyst' },
    { value: 'Recruitment and Staffing Clerk', label: 'Recruitment and Staffing Clerk' },
    { value: 'Recruitment and Staffing Coord', label: 'Recruitment and Staffing Coord' },
    { value: 'Recruitment and Staffing Super', label: 'Recruitment and Staffing Super' },
    { value: 'Research Analyst', label: 'Research Analyst' },
    { value: 'Research and Project Support', label: 'Research and Project Support' },
    { value: 'Senior Budget Analyst', label: 'Senior Budget Analyst' },
    { value: 'Senior Business Analyst', label: 'Senior Business Analyst' },
    { value: 'Senior Data Analyst', label: 'Senior Data Analyst' },
    { value: 'Senior Data Architect', label: 'Senior Data Architect' },
    { value: 'Senior Investigator', label: 'Senior Investigator' },
    { value: 'Senior Ministry Investigator', label: 'Senior Ministry Investigator' },
    { value: 'Senior Policy & Program Spec', label: 'Senior Policy & Program Spec' },
    { value: 'Senior Policy & Proj Analyst', label: 'Senior Policy & Proj Analyst' },
    { value: 'Senior Program Analyst', label: 'Senior Program Analyst' },
    { value: 'Senior Project Mgmt Analyst', label: 'Senior Project Mgmt Analyst' },
    { value: 'Snr Data Architect&Data Scient', label: 'Snr Data Architect&Data Scient' },
    { value: 'Sr Bus Intelligence Analyst', label: 'Sr Bus Intelligence Analyst' },
    { value: 'Sr Facilities & Asset Coord', label: 'Sr Facilities & Asset Coord' },
    { value: 'Sr Financial Contract Analyst', label: 'Sr Financial Contract Analyst' },
    { value: 'Sr Mgr, Comnty Rltns & Prgm Co', label: 'Sr Mgr, Comnty Rltns & Prgm Co' },
    { value: 'Sr Mgr, Policy Interp & Implem', label: 'Sr Mgr, Policy Interp & Implem' },
    { value: 'Sr Policy & Project Analyst', label: 'Sr Policy & Project Analyst' },
    { value: 'Sr Policy & Project Specialist', label: 'Sr Policy & Project Specialist' },
    { value: 'Sr Project Management Advisor', label: 'Sr Project Management Advisor' },
    { value: 'Sr Records Management Analyst', label: 'Sr Records Management Analyst' },
    { value: 'Sr. Financial Contract Analyst', label: 'Sr. Financial Contract Analyst' },
    { value: 'Sup Criminal Investigations', label: 'Sup Criminal Investigations' },
    { value: 'Supervisor, Admin Services', label: 'Supervisor, Admin Services' },
    { value: 'Supervisor, Business Insights', label: 'Supervisor, Business Insights' },
    { value: 'Supervisor, Prevent & Compl', label: 'Supervisor, Prevent & Compl' },
    { value: 'Supervisor, Program Support', label: 'Supervisor, Program Support' },
    { value: 'Supervisor, Service Delivery', label: 'Supervisor, Service Delivery' },
    { value: 'Team Lead, Program Evaluation', label: 'Team Lead, Program Evaluation' },
    { value: 'Trainer', label: 'Trainer' },
    { value: 'Training Coordinator', label: 'Training Coordinator' },
    { value: 'Training Specialist', label: 'Training Specialist' },
    { value: 'Unit Administrator', label: 'Unit Administrator' },
    { value: 'Workplace Health Advisor', label: 'Workplace Health Advisor' },
    { value: 'Other', label: 'Other' }
  ];

const JobTitleDropdown = ({ id, name, value, onChange }) => {
  return (
    <div>
      <label htmlFor={id}>Employee Job Title:</label>
      <br></br>
      <select id={id} name={name} value={value} onChange={onChange}>
        {jobTitleOptions.map((option) => (
          <option key={option.value || 'default'} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </div>
  );
};

export default JobTitleDropdown;
