import React from 'react';

const jobTitleOptions = [
    { value: '', label: 'Please Select:' },
    { value: 'Adjudicator', label: 'Adjudicator' },
    { value: 'ADM Service Delivery Division', label: 'ADM Service Delivery Division' },
    { value: 'Admin & Asset Administrator', label: 'Admin & Asset Administrator' },
    { value: 'Administrative Assistant', label: 'Administrative Assistant' },
    { value: 'Assistant Supervisor', label: 'Assistant Supervisor' },
    { value: 'Branch Coordinator', label: 'Branch Coordinator' },
    { value: 'Business Application Admin', label: 'Business Application Admin' },
    { value: 'Business Data Analyst', label: 'Business Data Analyst' },
    { value: 'Client Service Representative', label: 'Client Service Representative' },
    { value: 'Client Service Worker', label: 'Client Service Worker' },
    { value: 'Community Relations & Stakeholder Analysis', label: 'Community Relations & Stakeholder Analysis' },
    { value: 'Communications & Engagement Analyst', label: 'Communications & Engagement Analyst' },
    { value: 'Communications Analyst', label: 'Communications Analyst' },
    { value: 'Community Integration Special', label: 'Community Integration Special' },
    { value: 'Contract Analyst', label: 'Contract Analyst' },
    { value: 'Data Analyst', label: 'Data Analyst' },
    { value: 'Director, Partnership, Performance & Practice', label: 'Director, Partnership, Performance & Practice' },
    { value: 'Director, Strategic Projects & Technology Integration', label: 'Director, Strategic Projects & Technology Integration' },
    { value: 'Director, Strategic Partnerships & Communications', label: 'Director, Strategic Partnerships & Communications' },
    { value: 'Director, Community Engagement & Organizational Health', label: 'Director, Community Engagement & Organizational Health' },
    { value: 'Director, Knowledge Management', label: 'Director, Knowledge Management' },
    { value: 'Director, ABI', label: 'Director, ABI' },
    { value: 'Director, Criminal Operations', label: 'Director, Criminal Operations' },
    { value: 'Director, FCRM', label: 'Director, FCRM' },
    { value: 'Director, Operations', label: 'Director, Operations' },
    { value: 'Director, Program Integrity & Evaluation', label: 'Director, Program Integrity & Evaluation' },
    { value: 'Director, RSFA', label: 'Director, RSFA' },
    { value: 'Director, Service Delivery', label: 'Director, Service Delivery' },
    { value: 'Employment & Assistance Worker', label: 'Employment & Assistance Worker' },
    { value: 'Executive Administrative Assistant', label: 'Executive Administrative Assistant' },
    { value: 'Executive Director, Community Integration Services', label: 'Executive Director, Community Integration Services' },
    { value: 'Executive Director, Operations Support', label: 'Executive Director, Operations Support' },
    { value: 'Executive Director, PLMS', label: 'Executive Director, PLMS' },
    { value: 'Executive Director, SD', label: 'Executive Director, SD' },
    { value: 'Executive Director, SS', label: 'Executive Director, SS' },
    { value: 'Facilities & Assets Admin', label: 'Facilities & Assets Admin' },
    { value: 'Facilities & Assets Coordinator', label: 'Facilities & Assets Coordinator' },
    { value: 'Financial Analyst', label: 'Financial Analyst' },
    { value: 'Full Stack Developer', label: 'Full Stack Developer' },
    { value: 'Job Resources Analyst', label: 'Job Resources Analyst' },
    { value: 'Job Resources Lead', label: 'Job Resources Lead' },
    { value: 'Junior Performance Analyst', label: 'Junior Performance Analyst' },
    { value: 'Junior Program Analyst', label: 'Junior Program Analyst' },
    { value: 'Lead Trainer', label: 'Lead Trainer' },
    { value: 'Major Case File Specialist', label: 'Major Case File Specialist' },
    { value: 'Manager, Learning & Development', label: 'Manager, Learning & Development' },
    { value: 'Manager, Strateg Plan & Project', label: 'Manager, Strateg Plan & Project' },
    { value: 'Manager, Analytics & BI', label: 'Manager, Analytics & BI' },
    { value: 'Manager, Contracts', label: 'Manager, Contracts' },
    { value: 'Manager, Criminal Operations', label: 'Manager, Criminal Operations' },
    { value: 'Manager, Data & Evaluation', label: 'Manager, Data & Evaluation' },
    { value: 'Manager, Facilities & Assets', label: 'Manager, Facilities & Assets' },
    { value: 'Manager, Financial Services', label: 'Manager, Financial Services' },
    { value: 'Manager, Operations', label: 'Manager, Operations' },
    { value: 'Manager, Policy & Program Implementation', label: 'Manager, Policy & Program Implementation' },
    { value: 'Manager, Program Evaluation', label: 'Manager, Program Evaluation' },
    { value: 'Manager, Program Integrity', label: 'Manager, Program Integrity' },
    { value: 'Manager, Recruitment', label: 'Manager, Recruitment' },
    { value: 'Manager, SD & Program Development', label: 'Manager, SD & Program Development' },
    { value: 'Manager, Senior Project', label: 'Manager, Senior Project' },
    { value: 'Manager, Service Delivery', label: 'Manager, Service Delivery' },
    { value: 'Manager, Staffing', label: 'Manager, Staffing' },
    { value: 'Manager, Strategic Issues', label: 'Manager, Strategic Issues' },
    { value: 'Manager, Trainer Program', label: 'Manager, Trainer Program' },
    { value: 'Manager, Business Technology Integration', label: 'Manager, Business Technology Integration' },
    { value: 'Manager, Program Evaluation & Reporting', label: 'Manager, Program Evaluation & Reporting' },
    { value: 'Manager, Community Relations & Service Quality', label: 'Manager, Community Relations & Service Quality' },
    { value: 'Manager, Organizational Health & Development', label: 'Manager, Organizational Health & Development' },
    { value: 'Manager, Partnerships & Practice', label: 'Manager, Partnerships & Practice' },
    { value: 'Marketing Leader', label: 'Marketing Leader' },
    { value: 'Ministry Investigator', label: 'Ministry Investigator' },
    { value: 'Operations Support Clerk', label: 'Operations Support Clerk' },
    { value: 'Policy & Communications Coordinator', label: 'Policy & Communications Coordinator' },
    { value: 'Policy & Project Analyst', label: 'Policy & Project Analyst' },
    { value: 'Policy Interpretation & Coordination Analyst', label: 'Interpretation & Coordination Analyst' },
    { value: 'Process & Project Analyst', label: 'Process & Project Analyst' },
    { value: 'Program & Policy Analyst', label: 'Program & Policy Analyst' },
    { value: 'Program Evaluation Analyst', label: 'Program Evaluation Analyst' },
    { value: 'Program Evaluation Specialist', label: 'Program Evaluation Specialist' },
    { value: 'Program Specialist', label: 'Program Specialist' },
    { value: 'Program Support Clerk', label: 'Program Support Clerk' },
    { value: 'Program Support Supervisor', label: 'Program Support Supervisor' },
    { value: 'Project Analyst', label: 'Project Analyst' },
    { value: 'Project Management & Analysis Support', label: 'Project Management & Analysis Support' },
    { value: 'Project Management Analyst', label: 'Project Management Analyst' },
    { value: 'Project Support Analyst', label: 'Project Support Analyst' },
    { value: 'Project Support Intern', label: 'Project Support Intern' },
    { value: 'Quality & Compliance Spec', label: 'Quality & Compliance Spec' },
    { value: 'Records Clerk', label: 'Records Clerk' },
    { value: 'Records Management Supervisor', label: 'Records Management Supervisor' },
    { value: 'Recruitment & Staffing Analyst', label: 'Recruitment & Staffing Analyst' },
    { value: 'Recruitment & Staffing Clerk', label: 'Recruitment & Staffing Clerk' },
    { value: 'Recruitment & Staffing Coordinator', label: 'Recruitment & Staffing Coordinator' },
    { value: 'Recruitment & Staffing Supervisor', label: 'Recruitment & Staffing Supervisor' },
    { value: 'Research Analyst', label: 'Research Analyst' },
    { value: 'Research & Project Support', label: 'Research & Project Support' },
    { value: 'Senior Budget Analyst', label: 'Senior Budget Analyst' },
    { value: 'Senior Business Analyst', label: 'Senior Business Analyst' },
    { value: 'Senior Data Analyst', label: 'Senior Data Analyst' },
    { value: 'Senior Data Architect', label: 'Senior Data Architect' },
    { value: 'Senior Investigator', label: 'Senior Investigator' },
    { value: 'Senior Ministry Investigator', label: 'Senior Ministry Investigator' },
    { value: 'Senior Policy & Program Specialist', label: 'Senior Policy & Program Specialist' },
    { value: 'Senior Policy & Project Analyst', label: 'Senior Policy & Project Analyst' },
    { value: 'Senior Program Analyst', label: 'Senior Program Analyst' },
    { value: 'Senior Project Management Analyst', label: 'Senior Project Management Analyst' },
    { value: 'Senior Data Architect & Data Scientist', label: 'Senior Data Architect & Data Scientist' },
    { value: 'Senior Business Intelligence Analyst', label: 'Senior Business Intelligence Analyst' },
    { value: 'Senior Facilities & Asset Coordinator', label: 'Senior Facilities & Asset Coordinator' },
    { value: 'Senior Financial Contract Analyst', label: 'Senior Financial Contract Analyst' },
    { value: 'Senior Manager, Community Relations & Program Coordinatoin', label: 'Senior Manager, Community Relations & Program Coordinatoin' },
    { value: 'Senior Manager, Policy Interpretation & Implementation', label: 'Senior Manager, Policy Interpretation & Implementation' },
    { value: 'Senior Policy & Project Analyst', label: 'Senior Policy & Project Analyst' },
    { value: 'Senior Policy & Project Specialist', label: 'Senior Policy & Project Specialist' },
    { value: 'Senior Project Management Advisor', label: 'Senior Project Management Advisor' },
    { value: 'Senior Records Management Analyst', label: 'Senior Records Management Analyst' },
    { value: 'Senior Financial Contract Analyst', label: 'Senior Financial Contract Analyst' },
    { value: 'Supervisor Criminal Investigations', label: 'Supervisor Criminal Investigations' },
    { value: 'Supervisor, Admin Services', label: 'Supervisor, Admin Services' },
    { value: 'Supervisor, Business Insights', label: 'Supervisor, Business Insights' },
    { value: 'Supervisor, Prevent & Compl', label: 'Supervisor, Prevent & Compl' },
    { value: 'Supervisor, Program Support', label: 'Supervisor, Program Support' },
    { value: 'Supervisor, Service Delivery', label: 'Supervisor, Service Delivery' },
    { value: 'Team Lead, Program Evaluation', label: 'Team Lead, Program Evaluation' },
    { value: 'Trainer', label: 'Trainer' },
    { value: 'Training Coordinator', label: 'Training Coordinator' },
    { value: 'Training Specialist', label: 'Training Specialist' },
    { value: 'Unit Administrator', label: 'Unit Administrator' },
    { value: 'Workplace Health Advisor', label: 'Workplace Health Advisor' },
    { value: 'Other', label: 'Other' }
  ];

const JobTitleDropdown = ({ id, name, value, onChange }) => {
  return (
    <div>
      <label htmlFor={id}>Employee Job Title:</label>
      <br></br>
      <select id={id} name={name} value={value} onChange={onChange}>
        {jobTitleOptions.map((option) => (
          <option key={option.value || 'default'} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </div>
  );
};

export default JobTitleDropdown;
