const jobTitleMapping = {
    "Adjudicator": "ADMN O 18R",
    "ADM Service Delivery Division": "ADM1",
    "Admin & Asset Administrator": "CLK 12R",
    "Administrative Assistant": "CLK ST 09R",
    "Assistant Supervisor": "CPO-IA 21R",
    "Branch Coordinator": "CLK ST 12R",
    "Business Application Admin": "ADMN O 15R",
    "Business Data Analyst": "FO 18R",
    "Client Service Representative": "CLK 09R",
    "Client Service Worker": "CLK 09R",
    "Comm Relat and Stakehol Analys": "ADMN O 24R",
    "Comms & Engagement Analyst": "COMM O 18R",
    "Communications Analyst": "COMM O 18R",
    "Community Integration Special": "CPO 18R",
    "Contract Analyst": "ADMN O 18R",
    "Data Analyst": "RES O 21R",
    "Dir Partnership, Perf & Prac": "Band 4",
    "Dir, Strat Proj & Tech Integra": "Band 4",
    "Dir, Strategic Partner & Comms": "Band 4",
    "Dir. Comm Engage & Org Health": "Band 3",
    "Dir. Knowledge Management": "Band 3",
    "Director, ABI": "Band 4",
    "Director, Criminal Operations": "Band 4",
    "Director, FCRM": "Band 4",
    "Director, Operations": "Band 4",
    "Director, Prg Integrity & Eval": "Band 4",
    "Director, RSFA": "Band 4",
    "Director, Service Delivery": "Band 4",
    "ED, Community Integration Serv": "Band 6",
    "Employment & Assistance Worker": "CPO-EA 15R",
    "Exec Dir Operations Support": "Band 5",
    "Executive Administrative Asst": "EXEC ADMIN",
    "Executive Director, PLMS": "Band 5",
    "Executive Director, SD": "Band 6",
    "Executive Director, SS": "Band 5",
    "Facilities & Asset Admin": "CLK 12R",
    "Facilities &Assets Coordinator": "CLK 15R",
    "Financial Analyst": "FO 18R",
    "Full Stack Developer": "ISL 27R",
    "Job Resources Analyst": "ADMN O 18R",
    "Job Resources Lead": "ADMN O 24R",
    "Jr Performance Analyst": "RES O 18R",
    "Junior Program Analyst": "EQU INTERN",
    "Lead Trainer": "ADMN O 21R",
    "Major Case File Specialist": "ADMN O 18R",
    "Manager Learning & Development": "Band 2",
    "Manager Strateg Plan & Project": "Band 2",
    "Manager, Analytics and BI": "Band 3",
    "Manager, Contracts": "Band 3",
    "Manager, Criminal Operations": "Band 3",
    "Manager, Data & Evaluation": "Band 3",
    "Manager, Facilities and Assets": "Band 3",
    "Manager, Financial Services": "Band 3",
    "Manager, Operations": "Band 3",
    "Manager, Policy & Pgm Impl": "Band 2",
    "Manager, Program Evaluation": "Band 3",
    "Manager, Program Integrity": "Band 3",
    "Manager, Recruitment": "Band 3",
    "Manager, SD & Program Devel": "Band 3",
    "Manager, Senior Project": "Band 2",
    "Manager, Service Delivery": "Band 3",
    "Manager, Staffing": "Band 3",
    "Manager, Strategic Issues": "Band 2",
    "Manager, Trainer Program": "Band 2",
    "Marketing Leader": "ADMN O 21R",
    "Mgr Bus Technology Integration": "Band 3",
    "Mgr Prgm Evaluation & Reportng": "Band 3",
    "Mgr, Comm Rel & Service Qual": "Band 2",
    "Mgr, Org Health & Development": "Band 2",
    "Mgr, Partnerships & Practice": "Band 3",
    "Ministry Investigator": "ADMN O 21R",
    "Operations Support Clerk": "CLK 09R",
    "Policy & Comms Coordinator": "ADMN O 18R",
    "Policy & Project Analyst": "ADMN O 21R",
    "Policy Interp & Coord Analyst": "ADMN O 18R",
    "Process & Project Analyst": "ADMN O 18R",
    "Prog and Policy Analyst (Dev)": "ADMN O 24R",
    "Program and Policy Analyst": "ADMN O 24R",
    "Program Evaluation Analyst": "ADMN O 24R",
    "Program Evaluation Specialist": "RES O 18R",
    "Program Specialist": "ADMN O 18R",
    "Program Support Clerk": "CLK 09R",
    "Program Support Supervisor": "CLK 15R",
    "Proj Mgmt and Analysis Support": "WAIP",
    "Project Analyst": "ADMN O 18R",
    "Project Management Analyst": "ADMN O 21R",
    "Project Support Analyst": "EQU INTERN",
    "Project Support Intern": "IY INTERN",
    "Quality and Compliance Spec": "AO-IO R18",
    "Records Clerk": "CLK 09R",
    "Records Management Supervisor": "CLK 15R",
    "Recruitment & Staffing Analyst": "FO 18R",
    "Recruitment and Staffing Clerk": "CLK 09R",
    "Recruitment and Staffing Coord": "CLK 15R",
    "Recruitment and Staffing Super": "ADMN O 24R",
    "Research Analyst": "RES O 21R",
    "Research and Project Support": "WAIP",
    "Senior Budget Analyst": "FO 24R",
    "Senior Business Analyst": "ADMN O 24R",
    "Senior Data Analyst": "RES O 24R",
    "Senior Data Architect": "ISL 27R",
    "Senior Investigator": "ADMN O 24R",
    "Senior Ministry Investigator": "ADMN O 24R",
    "Senior Policy & Program Spec": "POL SI 27R",
    "Senior Policy & Proj Analyst": "ADMN O 24R",
    "Senior Program Analyst": "ADMN O 24R",
    "Senior Project Mgmt Analyst": "ADMN O 24R",
    "Snr Data Architect&Data Scient": "ISL 27R",
    "Sr Bus Intelligence Analyst": "RES O 24R",
    "Sr Facilities & Asset Coord": "ADMN O 18R",
    "Sr Financial Contract Analyst": "ADMN O 24R",
    "Sr Mgr, Comnty Rltns & Prgm Co": "Band 3",
    "Sr Mgr, Policy Interp & Implem": "Band 3",
    "Sr Policy & Project Analyst": "ADMN O 24R",
    "Sr Policy & Project Specialist": "POL SI 27R",
    "Sr Project Management Advisor": "ADMN O 24R",
    "Sr Records Management Analyst": "ADMN O 21R",
    "Sr. Financial Contract Analyst": "ADMN O 24R",
    "Sup Criminal Investigations": "ADMN O 27R",
    "Supervisor, Admin Services": "CLK 15R",
    "Supervisor, Business Insights": "ADMN O 24R",
    "Supervisor, Prevent & Compl": "ADMN O 24R",
    "Supervisor, Program Support": "CLK 15R",
    "Supervisor, Service Delivery": "CPO-IA 24R",
    "Team Lead, Program Evaluation": "ADMN O 24R",
    "Trainer": "ADMN O 18R",
    "Training Coordinator": "ADMN O 15R",
    "Training Specialist": "ADMN O 21R",
    "Unit Administrator": "CLK 12R",
    "Workplace Health Advisor": "ADMN O 18R",
    "Other": "-"
  };
  
  export default jobTitleMapping;
  