import React from 'react';

const programAreaOptions = [
    { value: '', label: 'Please Select:' },
    { value: 'CS - Area A Management', label: 'CS - Area A Management' },
    { value: 'CS - Vefra - Victoria', label: 'CS - Vefra - Victoria' },
    { value: 'CS - Gateway - Victoria', label: 'CS - Gateway - Victoria' },
    { value: 'CS - Nanaimo South', label: 'CS - Nanaimo South' },
    { value: 'CS - Nanaimo North', label: 'CS - Nanaimo North' },
    { value: 'CS - Port Alberni', label: 'CS - Port Alberni' },
    { value: 'CS - Abbotsford', label: 'CS - Abbotsford' },
    { value: 'CS - Courtenay', label: 'CS - Courtenay' },
    { value: 'CS - Powell River', label: 'CS - Powell River' },
    { value: 'CS - Campbell River', label: 'CS - Campbell River' },
    { value: 'CS - Duncan', label: 'CS - Duncan' },
    { value: 'CS - Mission', label: 'CS - Mission' },
    { value: 'CS - Maple Ridge', label: 'CS - Maple Ridge' },
    { value: 'CS - Sechelt', label: 'CS - Sechelt' },
    { value: 'CS - Reports, Utilities and ID Team', label: 'CS - Reports, Utilities and ID Team' },
    { value: 'CS - Langley', label: 'CS - Langley' },
    { value: 'CS - Chilliwack', label: 'CS - Chilliwack' },
    { value: 'CS - Hope', label: 'CS - Hope' },
    { value: 'CS - Tri-Cities', label: 'CS - Tri-Cities' },
    { value: 'CS - Area B Management', label: 'CS - Area B Management' },
    { value: 'CS - Cranbrook', label: 'CS - Cranbrook' },
    { value: 'CS - Grand Forks SBC', label: 'CS - Grand Forks SBC' },
    { value: 'CS - Trail', label: 'CS - Trail' },
    { value: 'CS - Nelson', label: 'CS - Nelson' },
    { value: 'CS - Oliver', label: 'CS - Oliver' },
    { value: 'CS - Penticton', label: 'CS - Penticton' },
    { value: 'CS - Westbank', label: 'CS - Westbank' },
    { value: 'CS - Kelowna', label: 'CS - Kelowna' },
    { value: 'CS - Vernon', label: 'CS - Vernon' },
    { value: 'CS - Salmon Arm', label: 'CS - Salmon Arm' },
    { value: 'CS - Kamloops South', label: 'CS - Kamloops South' },
    { value: 'CS - Kamloops North', label: 'CS - Kamloops North' },
    { value: 'CS - Merritt SBC', label: 'CS - Merritt SBC' },
    { value: 'CS - 100 Mile House', label: 'CS - 100 Mile House' },
    { value: 'CS - Williams Lake', label: 'CS - Williams Lake' },
    { value: 'CS - Quesnel', label: 'CS - Quesnel' },
    { value: 'CS - Dawson Creek', label: 'CS - Dawson Creek' },
    { value: 'CS - Fort St John', label: 'CS - Fort St John' },
    { value: 'CS - Prince George', label: 'CS - Prince George' },
    { value: 'CS - Vanderhoof SBC', label: 'CS - Vanderhoof SBC' },
    { value: 'CS - Smithers', label: 'CS - Smithers' },
    { value: 'CS - Terrace', label: 'CS - Terrace' },
    { value: 'CS - Prince Rupert', label: 'CS - Prince Rupert' },
    { value: 'CS - Service BC Support Team', label: 'CS - Service BC Support Team' },
    { value: 'CS - Change in Circumstance Team', label: 'CS - Change in Circumstance Team' },
    { value: 'CS - File Review Team', label: 'CS - File Review Team' },
    { value: 'CS - Admin Underpayment Team', label: 'CS - Admin Underpayment Team' },
    { value: 'CS - Area C Management', label: 'CS - Area C Management' },
    { value: 'CS - Richmond', label: 'CS - Richmond' },
    { value: 'CS - Dockside', label: 'CS - Dockside' },
    { value: 'CS - Strathcona', label: 'CS - Strathcona' },
    { value: 'CS - Kiwassa', label: 'CS - Kiwassa' },
    { value: 'CS - Grandview', label: 'CS - Grandview' },
    { value: 'CS - New Westminster', label: 'CS - New Westminster' },
    { value: 'CS - Mountainview', label: 'CS - Mountainview' },
    { value: 'CS - West End', label: 'CS - West End' },
    { value: 'CS - Burnaby Metro Pointe', label: 'CS - Burnaby Metro Pointe' },
    { value: 'CS - North Van', label: 'CS - North Van' },
    { value: 'CS - Fleetwood', label: 'CS - Fleetwood' },
    { value: 'CS - Surrey North', label: 'CS - Surrey North' },
    { value: 'CS - Park Place', label: 'CS - Park Place' },
    { value: 'CISB - Management', label: 'CISB - Management' },
    { value: 'CISB - Performance and Reporting', label: 'CISB - Performance and Reporting' },
    { value: 'CISB - Practice and Partnerships', label: 'CISB - Practice and Partnerships' },
    { value: 'CISB - Management Service Delivery', label: 'CISB - Management Service Delivery' },
    { value: 'CISB - Van Island South', label: 'CISB - Van Island South' },
    { value: 'CISB - Fraser North', label: 'CISB - Fraser North' },
    { value: 'CISB - Fraser Surrey', label: 'CISB - Fraser Surrey' },
    { value: 'CISB - Interior North', label: 'CISB - Interior North' },
    { value: 'CISB - North', label: 'CISB - North' },
    { value: 'CISB - Van Downtown/DTES', label: 'CISB - Van Downtown/DTES' },
    { value: 'CISB - Van Island Central/North', label: 'CISB - Van Island Central/North' },
    { value: 'CISB - Interior South', label: 'CISB - Interior South' },
    { value: 'CISB - Van East/South Richmond', label: 'CISB - Van East/South Richmond' },
    { value: 'CISB - Van North Sunshine Sea-Sky', label: 'CISB - Van North Sunshine Sea-Sky' },
    { value: 'CISB - Fraser South', label: 'CISB - Fraser South' },
    { value: 'OSB - Finance, Contracts and Records Management', label: 'OSB - Finance, Contracts and Records Management' },
    { value: 'OSB - Recruitment, Staffing, Facilities and Assets', label: 'OSB - Recruitment, Staffing, Facilities and Assets' },
    { value: 'OSB - Analytics and Business Intelligence', label: 'OSB - Analytics and Business Intelligence' },
    { value: 'OSB - Communications, Engagement and Organizational Health', label: 'OSB - Communications, Engagement and Organizational Health' },
    { value: 'PLMS - Criminal Investigation Unit', label: 'PLMS - Criminal Investigation Unit' },
    { value: 'PLMS - Operations Management', label: 'PLMS - Operations Management' },
    { value: 'PLMS - Vancouver Island PLMS - Victoria', label: 'PLMS - Vancouver Island PLMS - Victoria' },
    { value: 'PLMS - Vancouver Island PLMS - Nanaimo', label: 'PLMS - Vancouver Island PLMS - Nanaimo' },
    { value: 'PLMS - START Task Team', label: 'PLMS - START Task Team' },
    { value: 'PLMS - Vancouver Coastal PLMS - Vancouver North', label: 'PLMS - Vancouver Coastal PLMS - Vancouver North' },
    { value: 'PLMS - Fraser PLMS - Fraser West', label: 'PLMS - Fraser PLMS - Fraser West' },
    { value: 'PLMS - Fraser PLMS - Fraser East', label: 'PLMS - Fraser PLMS - Fraser East' },
    { value: 'PLMS - Interior PLMS - Kelowna', label: 'PLMS - Interior PLMS - Kelowna' },
    { value: 'PLMS - North PLMS Regional Office', label: 'PLMS - North PLMS Regional Office' },
    { value: 'PLMS - Vancouver Coastal PLMS - Vancouver South', label: 'PLMS - Vancouver Coastal PLMS - Vancouver South' },
    { value: 'PLMS - Eligibility Reviews', label: 'PLMS - Eligibility Reviews' },
    { value: 'PLMS - Service Quality Unit', label: 'PLMS - Service Quality Unit' },
    { value: 'PLMS - Program Integrity & Evaluation', label: 'PLMS - Program Integrity & Evaluation' },
    { value: 'PLMS - Program Evaluation', label: 'PLMS - Program Evaluation' },
    { value: 'PLMS - Program Support', label: 'PLMS - Program Support' },
    { value: 'SSB - Strategic Partnerships and Communications', label: 'SSB - Strategic Partnerships and Communications' },
    { value: 'SSB - Strategic Projects & Technology Support', label: 'SSB - Strategic Projects & Technology Support' },
    { value: 'SSB - Knowledge Management', label: 'SSB - Knowledge Management' },
    { value: 'VS - Intake', label: 'VS - Intake' },
    { value: 'VS - Specialized Intake', label: 'VS - Specialized Intake' },
    { value: 'VS - Management Intake', label: 'VS - Management Intake' },
    { value: 'VS - Employment Plans', label: 'VS - Employment Plans' },
    { value: 'VS - Special Care Faclities', label: 'VS - Special Care Faclities' },
    { value: 'VS - Management Health and Specialized Services', label: 'VS - Management Health and Specialized Services' },
    { value: 'VS - Case Reviews', label: 'VS - Case Reviews' },
    { value: 'VS - OAS-GIS', label: 'VS - OAS-GIS' },
    { value: 'VS - Disablility Applications', label: 'VS - Disablility Applications' },
    { value: 'VS - Medical Equipment and Supplies', label: 'VS - Medical Equipment and Supplies' },
    { value: 'VS - Medical Transportation', label: 'VS - Medical Transportation' },
    { value: 'VS - Health Resource Team', label: 'VS - Health Resource Team' },
    { value: 'VS - Funeral Services', label: 'VS - Funeral Services' },
    { value: 'VS - Bus Pass', label: 'VS - Bus Pass' },
    { value: 'VS - Management Contact Centre', label: 'VS - Management Contact Centre' },
    { value: 'VS - Victoria CC', label: 'VS - Victoria CC' },
    { value: 'VS - Lower Mainland  CC', label: 'VS - Lower Mainland  CC' },
    { value: 'VS - Kamloops CC', label: 'VS - Kamloops CC' },
    { value: 'VS - PG CC', label: 'VS - PG CC' },
    { value: 'VS - Chilliwack Contact Centre', label: 'VS - Chilliwack Contact Centre' }
  ];

const ProgramAreaDropdown = ({ id, name, value, onChange }) => {
  return (
    <div>
      <label htmlFor={id}>Branch/Program Area:</label>
      <br></br>
      <select id={id} name={name} value={value} onChange={onChange}>
        {programAreaOptions.map((option) => (
          <option key={option.value || 'default'} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </div>
  );
};

export default ProgramAreaDropdown;
