apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-update-form
  labels:
    app.kubernetes.io/name: staff-update-form
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: staff-update-form
  template:
    metadata:
      labels:
        app.kubernetes.io/name: staff-update-form
    spec:
      containers:
        - name: staff-update-form
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources: {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always