replicaCount: 1

image:
  repository: ghcr.io/bcgov/this_is_the_repo_name
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}